DROP DATABASE IF EXISTS BD_Prestamo;
Create DATABASE BDPrestamo;

USE BD_Prestamo;
--CREAR TABLA 'CLIENTE'
CREATE TABLE CLIENTE
(
    COD_CLI INT AUTO_INCREMENT PRIMARY KEY,
    NOM_CLI VARCHAR(50),
    APE_CLI VARCHAR(50),
    DNI_CLI CHAR(8)
);
--INSERTAR DATA
INSERT INTO CLIENTE VALUES(NULL,'PEDRO','TIZNADO','12345678');
INSERT INTO CLIENTE VALUES(NULL,'JUAN','PEREZ','12345678');
INSERT INTO CLIENTE VALUES(NULL,'RAMIRO','ALVAREZ','12345678');

SELECT *FROM CLIENTE;

--CREAR PROCEDIMIENTO ALMACENADO SP_BUSDEL_CLIENTE
DROP PROCEDURE IF EXISTS SP_BUSDEL_CLIENTE;
DELIMITER $$
CREATE PROCEDURE SP_BUSDEL_CLIENTE
(BUS VARCHAR(20),TIPO VARCHAR(3))
BEGIN
    IF TIPO = 'B' THEN
        SELECT * FROM CLIENTE WHERE COD_CLI = BUS OR NOM_CLI LIKE CONCAT('%',BUS,'%');
    ELSEIF TIPO = 'D' THEN
        DELETE FROM CLIENTE WHERE COD_CLI = BUS;
    END IF;
END $$
DELIMITER $$
--CREAR PROCEDIMIENTO ALACENADO SP_BUSDEL_DISTRITO
DROP PROCEDURE IF EXISTS SP_BUSDEL_DISTRITO;
DELIMITER $$
CREATE PROCEDURE SP_BUSDEL_DISTRITO
(BUS VARCHAR(20),TIPO VARCHAR(3))
BEGIN
    IF TIPO = 'B' THEN
        SELECT * FROM DISTRITO WHERE COD_DIST = BUS OR NOM_DIST LIKE CONCAT('%',BUS,'%');
    ELSEIF TIPO = 'D' THEN
        DELETE FROM DISTRITO WHERE COD_DIST = BUS;
    END IF;
END $$
DELIMITER $$
--CREAR PROCEDIMIENTO ALACENADO SP_BUSDEL_EMPLEADO
DROP PROCEDURE IF EXISTS SP_BUSDEL_EMPLEADO;
DELIMITER $$
CREATE PROCEDURE SP_BUSDEL_EMPLEADO
(BUS VARCHAR(20),TIPO VARCHAR(3))
BEGIN
    IF TIPO = 'B' THEN
        SELECT * FROM EMPLEADO WHERE ID_EMP = BUS OR NOM_EMP LIKE CONCAT('%',BUS,'%');
    ELSEIF TIPO = 'D' THEN
        DELETE FROM EMPLEADO WHERE ID_EMP = BUS;
    END IF;
END $$
DELIMITER $$
--CREAR PROCEDIMIENTO ALACENADO SP_BUSDEL_TIPO_CAMBIO
DROP PROCEDURE IF EXISTS SP_BUSDEL_TIPO_CAMBIO;
DELIMITER $$
CREATE PROCEDURE SP_BUSDEL_TIPO_CAMBIO
(BUS VARCHAR(20),TIPO VARCHAR(3))
BEGIN
    IF TIPO = 'B' THEN
        SELECT * FROM TIPO_CAMBIO WHERE COD_TIP = BUS OR NOM_TIP LIKE CONCAT('%',BUS,'%');
    ELSEIF TIPO = 'D' THEN
        DELETE FROM TIPO_CAMBIO WHERE COD_TIP = BUS;
    END IF;
END $$
DELIMITER $$